/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mvt' at '12/22/16 12:16 AM' with Gradle 3.2.1
 *
 * @author mvt, @date 12/22/16 12:16 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
