package com.kediumm.kedsensorrest;
import org.testng.annotations.Test;

import com.kediumm.kedsensorrest.controller.core.Library;


/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'Mmiguel Vale Teixeira' at '12/22/16 12:16 AM' with Gradle 3.2.1
 *
 * 
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        //assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
